<?php

$SITEINFO_TITLE = '';
$SITEINFO_PHONE = '';
$SITEINFO_HP = '';
$SITEINFO_FAX = '';
$SITEINFO_EMAIL = '';
$SITEINFO_CUSTOMER_CENTER_ABLE_TIME = '';
$SITEINFO_COMPANY_ABLE_TIME = '';
$SITEINFO_GOOGLE_MAP_KEY = '';
$SITEINFO_LOGO_TOP = '';
$SITEINFO_LOGO_FOOTER = '';
$SITEINFO_FOOTER_NAME = '';
$SITEINFO_FOOTER_ADDRESS = '';
$SITEINFO_FOOTER_PHONE = '';
$SITEINFO_FOOTER_HP = '';
$SITEINFO_FOOTER_FAX = '';
$SITEINFO_FOOTER_EMAIL = '';
$SITEINFO_FOOTER_OWNER = '';
$SITEINFO_FOOTER_SSN = '';
$SITEINFO_FOOTER_CHARGER = '';
$SITEINFO_META_KEYWORDS = '';
$SITEINFO_META_DESCRIPTION = '';
$SITEINFO_META_THUMB = '';
$SITEINFO_META_FAVICON_ICO = '';

// DB 조회
$db = DB::getInstance();
$query = "SELECT * FROM nb_siteinfo WHERE sitekey = :sitekey";
$stmt = $db->prepare($query);
$stmt->bindValue(":sitekey", $NO_SITE_UNIQUE_KEY, PDO::PARAM_STR);
$stmt->execute();
$data_siteinfo = $stmt->fetch(PDO::FETCH_ASSOC);

// 값 할당
if ($data_siteinfo) {
    foreach ($data_siteinfo as $key => $value) {
        ${'SITEINFO_' . strtoupper($key)} = $value ?? '';
    }
}

// 메타 태그 변수 설정
$protocol = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https://' : 'http://';

$NO_STATIC_TITLE = $SITEINFO_TITLE;
$NO_META_KEYWORDS = $SITEINFO_META_KEYWORDS;
$NO_META_DESCRIPTION = $SITEINFO_META_DESCRIPTION;
$NO_META_URL = $protocol . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'];

$NO_META_TWITTER_CARD = "Summary";
$NO_META_TWITTER_URL = $NO_META_URL;
$NO_META_TWITTER_TITLE = $NO_STATIC_TITLE;
$NO_META_TWITTER_DESCRIPTION = $NO_META_DESCRIPTION;
$NO_META_TWITTER_IMAGE = $UPLOAD_META_WDIR . "/" . $SITEINFO_META_THUMB;

$NO_META_OG_URL = $protocol . $_SERVER['HTTP_HOST'];
$NO_META_OG_TYPE = "website";
$NO_META_OG_IMAGE = $NO_META_OG_URL . $UPLOAD_META_WDIR . "/" . $SITEINFO_META_THUMB;
$NO_META_OG_SITE_NAME = $NO_STATIC_TITLE;
$NO_META_OG_LOCALE = "ko";
$NO_META_OG_TITLE = $NO_STATIC_TITLE;
$NO_META_OG_DESCRIPTION = $NO_META_DESCRIPTION;

$NO_META_ITEMPROP_NAME = $NO_STATIC_TITLE;
$NO_META_ITEMPROP_IMAGE = "";
$NO_META_ITEMPROP_URL = $NO_META_URL;
$NO_META_ITEMPROP_DESCRIPTION = $NO_META_DESCRIPTION;
$NO_META_ITEMPROP_KEYWORD = $NO_META_KEYWORDS;

$NO_META_SHORTCUT_ICON = $UPLOAD_META_WDIR . "/" . $SITEINFO_META_FAVICON_ICO;
$NO_META_APPLE_TOUCH_ICON = "";